"""empty message

Revision ID: 9be11eef83b5
Revises: 
Create Date: 2018-03-26 09:28:53.757582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be11eef83b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=90), nullable=True),
    sa.Column('location', sa.String(length=90), nullable=True),
    sa.Column('bio', sa.String(length=1500), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('datte', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
